version: '3'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"  # 3000번 포트는 Next.js가 쓰고 있으므로 3001로 변경
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage: